# Generated by Django 6.0.2 on 2026-02-12 08:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0002_book_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowrecord',
            name='borrow_date',
        ),
        migrations.AddField(
            model_name='borrowrecord',
            name='borrowed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='borrowrecord',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
