# Generated by Django 5.2.11 on 2026-02-20 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0004_book_liked_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='likes',
        ),
    ]
