# Generated by Django 5.2.11 on 2026-02-20 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0005_remove_book_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='show_in',
            field=models.CharField(choices=[('navbar', 'Navbar'), ('home', 'Home Page')], default='home', max_length=10),
        ),
    ]
