# Generated by Django 6.0.2 on 2026-02-24 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0009_subscriber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='subscribed_at',
        ),
        migrations.AddField(
            model_name='subscriber',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
