# Generated by Django 6.0.2 on 2026-02-24 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0011_bookhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookhistory',
            name='reading_time',
            field=models.IntegerField(default=0),
        ),
    ]
