# Generated by Django 5.2.11 on 2026-02-25 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0013_shelf'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shelf',
        ),
    ]
